### PR TITLE
ryegen-init: build tags optional and non-default; ryegen: rework ryegen.Run, better names for native types, remove rye names for types, timing stats, simpler naming conflict resolution

### PR DESCRIPTION
**Pull request by xypwn**
This is mostly internal stuff, but it is crucial to support inline structs and improves maintainability (ryegen.Run used to be a complete mess)

### CODE REVIEW

**Review by refaktor — APPROVED** [review]
If I understand the changes you made it so that you can build multiple bindings for the same extended rye binary. Seems very useful change and more systematic. Great!

**Comment by xypwn** [comment]
How I understood it, building multiple bindings into a single binary was already possible (hence the build tag system?) [although I didn't actually ever try passing multiple build tags].

Mainly, the change is about assuming the user initially only wants to build a single binding into their repo, since, if that's the case, it's better not to mess with build tags. Using `go build` is a lot less confusing than needing to add `-tags ....` for the bindings to work.

**Comment by refaktor** [comment]
Sorry, I meant generating multiple bindings in one folder / project binary ... yes, building multiple with tags was always there. b_** build tags was initial way to select which modules Rye binary would have, but I was since persuaded, for Rye to remove this and just build with all modules that arent problematic to install, so now for basic Rye tags aren't needed. I changed it to `//go:build !no_sqlite` so you can exclude certain bindings with build tags.

In this manner I agree that it would also make sense that if you generate an externaly extended Rye, like Rye-fyne, that `go build` should be all you need, you already know you are building fyne so it makes no sense that you have to explicitly add it to build command. Maybe add no_ pattern so you can exlude it or specific modules in special cases if you need to.

**Comment by xypwn** [comment]
That actually makes a lot more sense! I'll add the no_ pattern as default.

**Pull request merged**
