### PR TITLE
Fixes: ellipsis type string, use make only for non-fixed arrays, deduplicate interface funcs

### PR DESCRIPTION
**Pull request by xypwn**
This makes go-imap generate valid Go code at least (but doesn't resolve the word/genword context priority bug)

### CODE REVIEW

**Comment by refaktor** [comment]
Wow, great! ... about the priority, for now at least, didn't you make ryegen in a way we can rename certain function using config.toml?

**Comment by xypwn** [comment]
> Wow, great! ... about the priority, for now at least, didn't you make ryegen in a way we can rename certain function using config.toml?

No, only exclude functions, but I can definitely implement that functionality, it shouldn't be too hard either.

**Comment by refaktor** [comment]
Hm ... I'm sure we were talking about it. Maybe you solved the concrete problem in other more general way, I think you added option to remove all prefixes or something similar. 

The renaming eventually will be needed I think, because we won't always want the exact naming of the binding. Some bindings are so big that we will adopt verbiage to them (fyne), but many are/will be "designed" to be Rye-first bindings and it doesn't matter what Go binding or multiple bindings are behind and we will want the wording and also how we call them customized to Rye standard wording. Some of these will be fixed by also writing custom Go binding functions.

But we can wait to decide until we really need it at concrete case, so we don't make things that just might be used. Unless this is current accepted solution for select/collect.

**Comment by xypwn** [comment]
> Hm ... I'm sure we were talking about it.

Quite possible... I guess I forgot about that part

I'll implement the renaming as well, since I agree, it would be pretty useful

**Pull request merged**
